---
homebrew_prefix: /usr/local
homebrew_clear_cache: false

# Taps
homebrew_taps: []
  # - name: varenc/ffmpeg                            # required
  #   url: https://github.com/varenc/homebrew-ffmpeg # optional
  #   state: present                                 # optional

# Brews
homebrew_brews: []
  # - description: Tesseract                         # optional
  #   name: tesseract                                # required
  #   options: all-languages                         # optional
  #   state: present                                 # optional

# Casks
homebrew_casks:
  # - description: Google Chrome                     # optional
  #   name: google-chrome                            # required
  #   options: appdir=/Applications                  # optional
  #   state: present                                 # optional
  #   accept_external_apps: true                     # optional

  # Microsoft Office 365:
  - description: Microsoft Office 365
    name: microsoft-office
    options: --verbose
    state: latest
    # accept_external_apps:
  - description: Microsoft Teams
    name: microsoft-teams
    # options:
    state: latest
    # accept_external_apps:
  - description: Microsoft Yammer
    name: yammer
    # options:
    state: latest
    # accept_external_apps:
  - description: Microsoft Skype
    name: skype
    # options:
    state: latest
    # accept_external_apps:

  # Office Tools
  - description: Grammarly
    name: grammarly
    # options:
    state: latest
    # accept_external_apps:

# MAS
mas_applications:
  # - name: google-chrome                            # optional
  #   id: 40923498                                   # required  
  - name: Microsoft To Do (2.14)
    id: 1274495053