---
homebrew_prefix: /usr/local
homebrew_clear_cache: false

# Taps
homebrew_taps: []
  # - name: varenc/ffmpeg                            # required
  #   url: https://github.com/varenc/homebrew-ffmpeg # optional
  #   state: present                                 # optional

# Brews
homebrew_brews: [] 
  # - description: Tesseract                         # optional
  #   name: tesseract                                # required
  #   options: all-languages                         # optional
  #   state: present                                 # optional

# Casks
homebrew_casks:
  # - description: Google Chrome                     # optional
  #   name: google-chrome                            # required
  #   options: appdir=/Applications                  # optional
  #   state: present                                 # optional
  #   accept_external_apps: true                     # optional

  #Entertainment:
  - description: Spotify
    name: spotify
    # options:
    state: latest
    # accept_external_apps:
  
# MAS
mas_applications:
  # - name: google-chrome                            # optional
  #   id: 40923498                                   # required  
  - name: GarageBand (10.3.4)
    id: 682658836
  - name: iMovie (10.1.14)
    id: 408981434
