---
homebrew_prefix: /usr/local
homebrew_clear_cache: false

# Taps
homebrew_taps: []
  # - name: varenc/ffmpeg                            # required
  #   url: https://github.com/varenc/homebrew-ffmpeg # optional
  #   state: present                                 # optional
# Brews
homebrew_brews: []
  # - description: Tesseract                         # optional
  #   name: tesseract                                # required
  #   options: all-languages                         # optional
  #   state: present                                 # optional

# Casks
homebrew_casks:
  # - description: Google Chrome                     # optional
  #   name: google-chrome                            # required
  #   options: appdir=/Applications                  # optional
  #   state: present                                 # optional
  #   accept_external_apps: true                     # optional

  #Games:
  - description: Steam
    name: steam
    # options:
    state: latest
    # accept_external_apps:
  - description: Shadow
    name: shadow-beta
    # options:
    state: latest
    # accept_external_apps:
  - description: Minecraft
    name: minecraft
    # options:
    state: latest
    # accept_external_apps:
  - description: Guild Wars 2
    name: guild-wars2
    # options:
    state: latest
    # accept_external_apps:
  - description: Blizzard Battle.net
    name: battle-net
    # options:
    state: latest
    # accept_external_apps:
  - description: League of Legends
    name: league-of-legends
    # options:
    state: latest
    # accept_external_apps:
  - description: Roblox
    name: roblox
    # options:
    state: latest
    # accept_external_apps:
