---
homebrew_prefix: /usr/local
homebrew_clear_cache: false

# Taps
homebrew_taps: []
  # - name: varenc/ffmpeg                            # required
  #   url: https://github.com/varenc/homebrew-ffmpeg # optional
  #   state: present                                 # optional

# Brews
homebrew_brews: 
  # - description: Tesseract                         # optional
  #   name: tesseract                                # required
  #   options: all-languages                         # optional
  #   state: present                                 # optional
  
  # Security:
  - description: SSH Copy ID
    name: ssh-copy-id
    # options:
    state: latest
  - description: SSH Vault
    name: ssh-vault
    # options:
    state: latest
  - description: SSHuttle
    name: sshuttle
    # options:
    state: latest

# Casks
homebrew_casks:
  # - description: Google Chrome                     # optional
  #   name: google-chrome                            # required
  #   options: appdir=/Applications                  # optional
  #   state: present                                 # optional
  #   accept_external_apps: true                     # optional

  # Security:
  - description: SSH Tunnel Manager
    name: ssh-tunnel-manager
    # options:
    state: latest
    # accept_external_apps:
  - description: GPG Suite
    name: gpg-suite
    # options:
    state: latest
    # accept_external_apps:
  - description: Dashlane
    name: dashlane
    # options:
    state: latest
    # accept_external_apps:
  - description: Avast Security
    name: avast-security
    # options:
    state: latest
    # accept_external_apps:
  - description: Express VPN
    name: expressvpn
    # options:
    state: latest
    # accept_external_apps:

# MAS
mas_applications: []
  # - name: google-chrome                            # optional
  #   id: 40923498                                   # required
