---
homebrew_prefix: /usr/local
homebrew_clear_cache: false

# Taps
homebrew_taps: []
  # - name: varenc/ffmpeg                            # required
  #   url: https://github.com/varenc/homebrew-ffmpeg # optional
  #   state: present                                 # optional

# Brews
homebrew_brews: 
  # - description: Tesseract                         # optional
  #   name: tesseract                                # required
  #   options: all-languages                         # optional
  #   state: present                                 # optional
  
  # Shell:
  - description: Fish Shell
    name: fish
    # options:
    state: latest
  - description: Nano
    name: nano
    # options:
    state: latest

# Casks
homebrew_casks:
  # - description: Google Chrome                     # optional
  #   name: google-chrome                            # required
  #   options: appdir=/Applications                  # optional
  #   state: present                                 # optional
  #   accept_external_apps: true                     # optional

  # Shell:
  - description: iTerm
    name: iterm2
    # options:
    state: latest
    # accept_external_apps:
  - description: Microsoft Powershell
    name: powershell
    # options:
    state: latest
    # accept_external_apps:

# MAS
mas_applications: []
  # - name: google-chrome                            # optional
  #   id: 40923498                                   # required