---

# Check if Homebrew is installed
- name: Check if Homebrew is installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_installed
  changed_when: false
  check_mode: no
  tags: [homebrew, configuration, install]

# Install Homebrew binaries
- name: Install Homebrew Binaries
  command: yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew
  when: not homebrew_installed.stat.exists
  tags: [homebrew, configuration, install]

# Update Homebrew binaries & Upgrade Packages
- name: Update Homebrew Binaries
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  tags: [homebrew, configuration, install, update]

# Ensure latest version of Homebrew Taps Packages
- name: Configure Homebrew Taps Packages
  homebrew_tap:
    name: "{{ item.name }}"
    url: "{{ item.url | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ homebrew_taps }}"
  notify:
    - Clear homebrew cache
  tags: [homebrew, configuration, install, update, test]

# Ensure latest version of Homebrew Packages
- name: install Homebrew Packages
  homebrew:
    name: "{{ item.name }}"
    url: "{{ item.url | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    options: "{{ item.options | default(omit) }}"
  with_items: "{{ homebrew_brews }}"
  notify:
    - Clear homebrew cache
  tags: [homebrew, install, update]

# Ensure latest version of Homebrew Casks Packages
- name: install Homebrew Casks Packages
  homebrew_cask:
    name: "{{ item.name }}"
    url: "{{ item.url | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ homebrew_casks}}"
  notify:
    - Clear homebrew cache
  tags: [homebrew, install, update]

# Ensure MAS is installed and up-to-date
- name: Ensure MAS is installed.
  homebrew: 
    name: mas
    state: latest

# Get already installed Apple App Store applications
- name: List installed Mac App Store apps
  command: "{{ homebrew_prefix }}/bin/mas list"
  register: mas_list
  changed_when: false
- debug:
    var: mas_list.stdout_lines

# Install missing Apple App Store applications
- name: Install apps from the Mac App Store
  command: "{{ homebrew_prefix }}/bin/mas install {{ item.id }}"
  with_items: "{{ mas_applications }}"
  when: item.id | string not in mas_list.stdout

# Ensure all Apple App Store applications are up-to-date
- name: Upgrade all apps (if configured).
  command: mas upgrade
  # when: mas_upgrade_all_apps